name: thermal_printer
description: "Thermal printer library that allows to print ZPL files by USB, Bluetooth or TCP/IP on thermal printers. Tested on Zebra ZD421 printer."
version: 1.0.0

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  usb_serial: ^0.5.2
  drago_usb_printer: ^0.0.8
  flutter_blue_plus: ^1.32.11
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
